### ISSUE TITLE
Uncaught TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by brunetto** [fradelg/atom-markmon-plugin#5]
[Enter steps to reproduce below:]
1. Just install it from atom settings

**Atom Version**: 1.0.19
**System**: Ubuntu 14.04.3
**Thrown From**: [markmon-preview](https://github.com/fradelg/atom-markmon-plugin) package, v0.9.1
### Stack Trace

Uncaught TypeError: Cannot read property 'prototype' of undefined

```
At /home/ziosi/.atom/packages/markmon-preview/lib/markmon-view.coffee:1

TypeError: Cannot read property 'prototype' of undefined
  at __extends (/home/ziosi/.atom/packages/markmon-preview/lib/markmon-view.coffee:4:199)
  at /home/ziosi/.atom/packages/markmon-preview/lib/markmon-view.coffee:11:3
  at Object.<anonymous> (/home/ziosi/.atom/packages/markmon-preview/lib/markmon-view.coffee:90:5)
  at Object.<anonymous> (/home/ziosi/.atom/packages/markmon-preview/lib/markmon-view.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (/home/ziosi/.atom/packages/markmon-preview/lib/markmon.coffee:1:15)
  at Object.<anonymous> (/home/ziosi/.atom/packages/markmon-preview/lib/markmon.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:761:34)
  at Package.module.exports.Package.activateConfig (/usr/share/atom/resources/app.asar/src/package.js:263:14)
  at PackageDetailView.module.exports.PackageDetailView.activateConfig (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:212:26)
  at PackageDetailView.module.exports.PackageDetailView.completeInitialzation (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:156:12)
  at PackageDetailView.module.exports.PackageDetailView.loadPackage (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:168:21)
  at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:298:17
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at PackageManager.module.exports.PackageManager.emitPackageEvent (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:588:27)
  at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:379:26
  at exit (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:60:16)
  at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:213:47)
  at /usr/share/atom/resources/app.asar/src/buffered-process.js:220:18
  at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:169:7)
  at Pipe._onclose (net.js:467:12)

```
### Commands

```
     -7:33.1.0 markdown-preview-katex:toggle (atom-text-editor.editor.is-focused)
     -7:14.4.0 core:select-all (atom-text-editor.editor.is-focused)
     -6:35.7.0 markdown-pdf:convert (atom-text-editor.editor.is-focused)
     -6:20 styleguide:show (atom-text-editor.editor.is-focused)
     -3:38.8.0 markdown-preview:toggle (atom-text-editor.editor.is-focused)
     -3:23.2.0 atom-math:toggle (atom-text-editor.editor.is-focused)
     -0:21.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "markdown-preview-katex",
      "markdown-themeable-pdf",
      "markdown-toc"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-math, v0.0.3
language-mathematica, v0.1.0
markdown-pdf, v1.3.9
mathjax-wrapper, v0.1.0

# Dev
No dev packages
```

**Comment by fradelg** [comment]
Please, give a try to the new version.

There were many issues with the new Atom 1.0 API that I tried to manage. Besides, I've added some improvement in the way that the markmon dependency is managed and how the markmon daemon is spawned.
